apiVersion: v1
kind: Service
metadata:
  name: app-three-service
spec:
  selector:
    app: app-three  # This service will automatically find pods with the label "app: app-three"
  ports:
    - protocol: TCP
      port: 80  # The service will be exposed on port 80 "INSIDE" the cluster
      targetPort: 80  # The service will "ROUTE TRAFFIC" to containers running on port 80